### ISSUE TITLE
Other point cloud file formats / Mesh generation

### ISSUE THREAD

**Issue by A-z-z-y** [Kenneth-Schroeder/ScanKit#3]
Are there plans to support exporting other point cloud formats such as .ply or .xyz, or mesh generation from said point clouds?

**Comment by Kenneth-Schroeder** [comment]
Hi @A-z-z-y,
unfortunately, there are currently no such plans.
The app is mainly intended for data collection to enable further processing externally.
Also, the time I have to work on this app is very limited. So I focus on keeping everything running smoothly instead of adding more features :)

Best,
Kenneth

**Comment by A-z-z-y** [comment]
Ahh alright, that makes sense. Have a great day!
